#!/usr/bin/env python3

#problem 44 pentagonal numbers
#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

def pentagon(n):
  return (n*(3*n-1)/2)

def find_pair(limit):

i=1
numbers=[]
for j in range(limit+1):
  numbers.append(pentagon(j))

while i<=limit:
  
